# Generated by Django 5.1.2 on 2024-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songUpload', '0003_alter_song_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
