# Generated by Django 5.1.2 on 2024-11-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songUpload', '0004_song_danceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
